src/Entity/Moderation/Report.php
<?php

namespace App\Entity\Moderation;

use App\Repository\Moderation\ReportRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ReportRepository::class)
 *
 * @ORM\Table(name="`tigerreports_reports`")
 */
class Report
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer", name="report_id")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $status;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $appreciation;

    /**
     * @ORM\Column(type="string", length=20)
     */
    private $date;

    /**
     * @ORM\Column(type="string", length=36)
     */
    private $reportedUuid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $reporterUuid;

    /**
     * @ORM\Column(type="string", length=150, nullable=true)
     */
    private $reason;

    /**
     * @ORM\Column(type="string", length=22, nullable=true)
     */
    private $reportedIp;

    /**
     * @ORM\Column(type="string", length=60, nullable=true)
     */
    private $reportedLocation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reportedMessages;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $reportedGamemode;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $reportedOnGround;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $reportedSneak;

    /**
     * @ORM\Column(type="string", length=1, nullable=true)
     */
    private $reportedSprint;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $ReportedHealth;

    /**
     * @ORM\Column(type="string", length=10, nullable=true)
     */
    private $reportedFood;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reportedEffects;

    /**
     * @ORM\Column(type="string", length=22)
     */
    private $reporterIp;

    /**
     * @ORM\Column(type="string", length=60)
     */
    private $reporterLocation;

    /**
     * @ORM\Column(type="text", nullable=true)
     */
    private $reporterMessages;

    /**
     * @ORM\Column(type="integer")
     */
    private $archived;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getAppreciation(): ?string
    {
        return $this->appreciation;
    }

    public function setAppreciation(?string $appreciation): self
    {
        $this->appreciation = $appreciation;

        return $this;
    }

    public function getDate(): ?string
    {
        return $this->date;
    }

    public function setDate(string $date): self
    {
        $this->date = $date;

        return $this;
    }

    public function getReportedUuid(): ?string
    {
        return $this->reportedUuid;
    }

    public function setReportedUuid(string $reportedUuid): self
    {
        $this->reportedUuid = $reportedUuid;

        return $this;
    }

    public function getReporterUuid(): ?string
    {
        return $this->reporterUuid;
    }

    public function setReporterUuid(string $reporterUuid): self
    {
        $this->reporterUuid = $reporterUuid;

        return $this;
    }

    public function getReason(): ?string
    {
        return $this->reason;
    }

    public function setReason(?string $reason): self
    {
        $this->reason = $reason;

        return $this;
    }

    public function getReportedIp(): ?string
    {
        return $this->reportedIp;
    }

    public function setReportedIp(?string $reportedIp): self
    {
        $this->reportedIp = $reportedIp;

        return $this;
    }

    public function getReportedLocation(): ?string
    {
        return $this->reportedLocation;
    }

    public function setReportedLocation(?string $reportedLocation): self
    {
        $this->reportedLocation = $reportedLocation;

        return $this;
    }

    public function getReportedMessages(): ?string
    {
        return $this->reportedMessages;
    }

    public function setReportedMessages(?string $reportedMessages): self
    {
        $this->reportedMessages = $reportedMessages;

        return $this;
    }

    public function getReportedGamemode(): ?string
    {
        return $this->reportedGamemode;
    }

    public function setReportedGamemode(?string $reportedGamemode): self
    {
        $this->reportedGamemode = $reportedGamemode;

        return $this;
    }

    public function getReportedOnGround(): ?string
    {
        return $this->reportedOnGround;
    }

    public function setReportedOnGround(?string $reportedOnGround): self
    {
        $this->reportedOnGround = $reportedOnGround;

        return $this;
    }

    public function getReportedSneak(): ?string
    {
        return $this->reportedSneak;
    }

    public function setReportedSneak(?string $reportedSneak): self
    {
        $this->reportedSneak = $reportedSneak;

        return $this;
    }

    public function getReportedSprint(): ?string
    {
        return $this->reportedSprint;
    }

    public function setReportedSprint(?string $reportedSprint): self
    {
        $this->reportedSprint = $reportedSprint;

        return $this;
    }

    public function getReportedHealth(): ?string
    {
        return $this->ReportedHealth;
    }

    public function setReportedHealth(?string $ReportedHealth): self
    {
        $this->ReportedHealth = $ReportedHealth;

        return $this;
    }

    public function getReportedFood(): ?string
    {
        return $this->reportedFood;
    }

    public function setReportedFood(?string $reportedFood): self
    {
        $this->reportedFood = $reportedFood;

        return $this;
    }

    public function getReportedEffects(): ?string
    {
        return $this->reportedEffects;
    }

    public function setReportedEffects(?string $reportedEffects): self
    {
        $this->reportedEffects = $reportedEffects;

        return $this;
    }

    public function getReporterIp(): ?string
    {
        return $this->reporterIp;
    }

    public function setReporterIp(string $reporterIp): self
    {
        $this->reporterIp = $reporterIp;

        return $this;
    }

    public function getReporterLocation(): ?string
    {
        return $this->reporterLocation;
    }

    public function setReporterLocation(string $reporterLocation): self
    {
        $this->reporterLocation = $reporterLocation;

        return $this;
    }

    public function getReporterMessages(): ?string
    {
        return $this->reporterMessages;
    }

    public function setReporterMessages(?string $reporterMessages): self
    {
        $this->reporterMessages = $reporterMessages;

        return $this;
    }

    public function getArchived(): ?int
    {
        return $this->archived;
    }

    public function setArchived(int $archived): self
    {
        $this->archived = $archived;

        return $this;
    }
}

src/Controller/Moderation/BanController.php
<?php

namespace App\Controller\Moderation;

use App\ControllerHandler\Moderation\BanHandler;
use App\Entity\Moderation\Ban;
use App\Form\Moderation\BanType;
use App\Repository\Moderation\BanRepository;
use App\Repository\Player\PlayersRepository;
use Exception;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/moderation/ban", name="moderation_ban_")
 */
class BanController extends AbstractController
{
    private BanRepository $banRepository;
    private PlayersRepository $playersRepository;
    private BanHandler $banHandler;

    public function __construct(
        BanRepository $banRepository,
        PlayersRepository $playersRepository,
        BanHandler $banHandler
    )
    {
        $this->banRepository = $banRepository;
        $this->playersRepository = $playersRepository;
        $this->banHandler = $banHandler;
    }

    /**
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     *
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(
        Request $request,
        PaginatorInterface $paginator
    ): Response
    {
        $bans = $this->banRepository->findAllDesc();

        $paginate = $paginator->paginate(
            $bans,
            $request->query->getInt('page', 1),
            20
        );

        return $this->render('moderation/ban/index.html.twig',[
            'bans' => $paginate,
            'players' => $this->playersRepository->findAll()
        ]);
    }

    /**
     * @param Request $request
     * @param UserInterface $user
     * @return Response
     * @throws Exception
     *
     * @Route("/new", name="new", methods={"GET", "POST"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function new(
        Request $request,
        UserInterface $user
    ): Response
    {
        $ban = new Ban();
        $form = $this->createForm(BanType::class, $ban)->handleRequest($request);

        if ($this->banHandler->createBanHandle($form, $ban, $user)) {
            $this->addFlash('success', sprintf(
                "Le ban du joueur avec l'uuid %s a bien été effectué",
                $ban->getUuid()
            ));

            return $this->redirectToRoute('moderation_ban_index');
        }

        return $this->render('moderation/ban/new.html.twig', [
            'form' => $form->createView(),
            'title' => 'Ajouter un ban'
        ]);
    }

    /**
     * @param Request $request
     * @param Ban $ban
     * @return Response
     * @throws Exception
     *
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function edit(
        Request $request,
        Ban $ban
    ): Response
    {
        $form = $this->createForm(BanType::class, $ban)->handleRequest($request);

        if ($this->banHandler->editBanHandle($form, $ban)) {
            $this->addFlash('success', sprintf(
                "Le ban du joueur avec l'uuid %s a bien été modifié",
                $ban->getUuid()
            ));

            return $this->redirectToRoute('moderation_ban_index');
        }

        return $this->render('moderation/ban/edit.html.twig', [
            'form' => $form->createView(),
            'title' => 'Modifier un ban'
        ]);
    }

    /**
     * @param Request $request
     * @param Ban $ban
     * @return Response
     *
     * @Route("/delete/{id}", name="delete", methods={"DELETE"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function delete(
        Request $request,
        Ban $ban
    ): Response
    {
        if ($this->isCsrfTokenValid('delete'.$ban->getId(), $request->request->get('_token'))) {
            $this->banHandler->deleteBanHandle($ban);

            $this->addFlash('success', sprintf(
                "Le ban du joueur avec l'uuid %s a bien été supprimé",
                $ban->getUuid()
            ));
        }

        return $this->redirectToRoute('moderation_ban_index');
    }

    /**
     * @param Ban $ban
     * @return Response
     *
     * @Route("/show/{id}", name="show", methods={"GET"})
     */
    public function show(
        Ban $ban
    ): Response
    {
        return $this->render('moderation/ban/show.html.twig', [
            'ban' => $ban,
            'firstPlayer' => $this->playersRepository->findOneBy(['lastip' => $ban->getBanIp()]),
            'playersByIp' => $this->playersRepository->findBy(['lastip' => $ban->getBanIp()]),
            'playerByUuid' => $this->playersRepository->findOneBy(['uuid' => $ban->getUuid()])
        ]);
    }
}

src/Controller/Moderation/CommentsController.php
<?php

namespace App\Controller\Moderation;

use App\ControllerHandler\Moderation\CommentsHandler;
use App\Entity\Moderation\Comments;
use App\Form\Moderation\CommentsType;
use App\Repository\Moderation\CommentsRepository;
use App\Repository\Player\PlayersRepository;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @Route("/moderation/comments", name="moderation_comments_")
 */
class CommentsController extends AbstractController
{
    private CommentsRepository $commentsRepository;
    private PlayersRepository $playersRepository;
    private CommentsHandler $commentsHandler;

    public function __construct(
        CommentsRepository $commentsRepository,
        PlayersRepository $playersRepository,
        CommentsHandler $commentsHandler
    ) {
        $this->commentsRepository = $commentsRepository;
        $this->playersRepository = $playersRepository;
        $this->commentsHandler = $commentsHandler;
    }


    /**
     * @param Request $request
     * @param PaginatorInterface $paginator
     * @return Response
     *
     * @Route("/", name="index", methods={"GET"})
     */
    public function index(
        Request $request,
        PaginatorInterface $paginator
    ): Response
    {
        $comments = $this->commentsRepository->findAllDesc();

        $paginate = $paginator->paginate(
            $comments,
            $request->query->getInt('page', 1),
            20
        );

        return $this->render('moderation/comments/index.html.twig', [
            'comments' => $paginate,
            'players' => $this->playersRepository->findAll()
        ]);
    }

    /**
     * @param Request $request
     * @param UserInterface $user
     * @return Response
     *
     * @Route("/new", name="new", methods={"GET", "POST"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function new(
        Request $request,
        UserInterface $user
    ): Response
    {
        $comments = new Comments();
        $form = $this->createForm(CommentsType::class, $comments)->handleRequest($request);

        if ($this->commentsHandler->createCommentsHandle($form, $comments, $user)) {
            $this->addFlash('success', sprintf(
                "Le commentaire du joueur avec l'uuid %s a bien été effectué",
                $comments->getEntity()
            ));

            return $this->redirectToRoute('moderation_comments_index');
        }

        return $this->render('moderation/comments/new.html.twig', [
            'form' => $form->createView(),
            'title' => 'Ajouter un commentaire'
        ]);
    }

    /**
     * @param Request $request
     * @param Comments $comments
     * @return Response
     *
     * @Route("/edit/{id}", name="edit", methods={"GET", "POST"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function edit(
        Request $request,
        Comments $comments
    ): Response
    {
        $form = $this->createForm(CommentsType::class, $comments)->handleRequest($request);

        if ($this->commentsHandler->editCommentsHandle($form, $comments)) {
            $this->addFlash('success', sprintf(
                "Le commentaire du joueur avec l'uuid %s a bien été modifié",
                $comments->getEntity()
            ));

            return $this->redirectToRoute('moderation_comments_index');
        }

        return $this->render('moderation/comments/edit.html.twig', [
            'form' => $form->createView(),
            'title' => 'Modifier le commentaire'
        ]);
    }

    /**
     * @param Request $request
     * @param Comments $comments
     * @return Response
     *
     * @Route("/delete/{id}", name="delete", methods={"DELETE"})
     *
     * @IsGranted("ROLE_RESP")
     */
    public function delete(
        Request $request,
        Comments $comments
    ): Response
    {
        if ($this->isCsrfTokenValid('delete'.$comments->getId(), $request->request->get('_token'))) {
            $this->commentsHandler->deleteCommentsHandle($comments);

            $this->addFlash('success', sprintf(
                "Le comments du joueur avec l'uuid %s a bien été supprimé",
                $comments->getEntity()
            ));
        }

        return $this->redirectToRoute('moderation_comments_index');
    }

    /**
     * @param Comments $comments
     * @return Response
     *
     * @Route("/show/{id}", name="show", methods={"GET"})
     */
    public function show(
        Comments $comments
    ): Response
    {
        return $this->render('moderation/comments/show.html.twig', [
            'comment' => $comments,
            'playerByUuid' => $this->playersRepository->findOneBy(['uuid' => $comments->getEntity()])
        ]);
    }
}

templates/moderation/report/index.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   <div>
      <h2 class="text-white text-center">Liste des Reports</h2>
   </div>
   <table class="table table-responsive-lg">
      <thead class="table-dark">
         <tr class="text-center">
            <th>Id</th>
            <th>Raison</th>
            <th>Signaleur</th>
            <th>Signalé</th>
            <th>Date</th>
         </tr>
      </thead>
      <tbody>
      {% for report in reports %}
         <tr class="bg-light text-center align-middle
            {% if report.appreciation|replace({'/': ' '})|truncate(4, true, '') == "True" %}
               {{ report.archived == 1 ? 'bg-table-report-true-archived' : 'bg-table-report-true' }}
            {% elseif report.appreciation == "False" %}
               {{ report.archived == 1 ? 'bg-table-report-false-archived' : 'bg-table-report-false' }}
            {% elseif report.appreciation == "Uncertain" %}
               {{ report.archived == 1 ? 'bg-table-report-uncertain-archived' : 'bg-table-report-uncertain' }}
            {% endif %}
         ">
            <th>{{ report.id }}</th>
            <th>
               <a href="{{ path('moderation_report_show', {'id': report.id}) }}">{{ report.reason }}</a>
            </th>
            <th>
               {% set replaceReporterUuid = report.reporterUuid|replace({'-': ''}) %}
               {% set splitReporterUuid = "" %}
               {% set reportersUuid = "" %}
               {% if replaceReporterUuid|length > 32 %}
                  {% set splitReporterUuid = replaceReporterUuid|split(',', 32) %}
               {% endif %}
               <img class="d-inline-block" src="https://cravatar.eu/head/{{ splitReporterUuid ? splitReporterUuid|first : report.reporterUuid }}/32" alt="">
               <span class="d-block">
                  {% set firstSplitReporterUuid = splitReporterUuid|first %}
                  {% set countReporterUuid = -1 %}
                  {% for nbReporterUuid in splitReporterUuid %}
                     {% set countReporterUuid = countReporterUuid + 1 %}
                  {% endfor %}
                  {% for player in players %}
                     {{ replaceReporterUuid == player.uuid ? player.batPlayer : '' }}
                     {{ firstSplitReporterUuid == player.uuid ? player.batPlayer : '' }}
                  {% endfor %}
               </span>
               {{ countReporterUuid == 1 ? '+1 joueur' : '' }}
               {{ countReporterUuid > 1 ? '+'~countReporterUuid~' joueurs' : '' }}
            </th>
            <th>
               <img class="d-inline-block" src="https://cravatar.eu/head/{{ report.reportedUuid }}/32" alt="">
               <span class="d-block">
                  {% set replaceReportedUuid = report.reportedUuid|replace({'-': ''}) %}
                  {% for player in players %}
                     {{ replaceReportedUuid == player.uuid ? player.batPlayer : '' }}
                  {% endfor %}
               </span>
            </th>
            <th>{{ report.date }}</th>
         </tr>
      {% else %}
         <tr>
            <td colspan="13">Aucune sanction actuellement</td>
         </tr>
      {% endfor %}
      </tbody>
   </table>
   <div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-true-archived"></span> Report valide archivé</div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-true"></span> Report valide</div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-false-archived"></span> Report non valide archivé</div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-false"></span> Report non valide</div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-uncertain-archived"></span> Report incertain archivé</div>
      <div class="d-inline-block text-demo-table"><span class="bg-demo-table-report-uncertain"></span> Report incertain</div>
   </div>
   <div class="navigation justify-content-center">
      {{ knp_pagination_render(reports, 'components/pagination.html.twig') }}
   </div>
{% endblock %}

templates/moderation/report/show.html.twig
{% extends 'base.html.twig' %}

{% block body %}
   <div class="container">
      <div class="bg-show-report">
         <h1 class="text-center">Information du report n°{{ report.id }}</h1>
         <h4 class="text-center"><b>Date :</b> {{ report.date }}</h4>
         <h4 class="text-center">
            {{ report.status != 'none' ? 'Traité par' : 'Pas encore traité' }}
            {% if report.status != 'none' %}
               {% for player in players %}
                  <b>{{ report.status|replace({'Done by ' : '', '-' : ''}) == player.uuid ? player.batPlayer : '' }}</b>
               {% endfor %}
            {% endif %}
         </h4>
         <h4 class="text-center">
            <b>Sanction appliqué :</b>
            {% if report.appreciation != 'True' and report.appreciation != 'False' and report.appreciation != 'Uncertain' %}
               {{ report.appreciation|replace({'True/': ' '})|title }}
            {% else %}
               Aucune
            {% endif %}
         </h4>
         <div class="row">
            <div class="col-lg-6 bd-show-report-left">
               <h4 class="text-center bd-show-report-title">Signaleur</h4>
               <div class="row m-0 p-0">
                  <div class="col-lg-4 bd-show-report-separate">
                     {% set replaceReporterUuid = report.reporterUuid|replace({'-': ''}) %}
                     {% set splitReporterUuid = "" %}
                     {% if replaceReporterUuid|length > 32 %}
                        {% set splitReporterUuid = replaceReporterUuid|split(',', 32) %}
                     {% endif %}
                     <img class="d-inline-block" src="https://cravatar.eu/head/{{ splitReporterUuid ? splitReporterUuid|first : report.reporterUuid }}/128" alt="">
                  </div>
                  <div class="col-lg-8 bd-show-report-separate">
                     <p>
                        <b>Signaleur : </b>
                        {% if splitReporterUuid %}
                           {% set countReporterUuid = 0 %}
                           {% for reporterUuid in splitReporterUuid %}
                              {% set countReporterUuid = countReporterUuid + 1 %}
                              {% for player in players %}
                                 {% if countReporterUuid > 1 %}
                                    {{ reporterUuid == player.uuid ? '/ '~player.batPlayer : '' }}
                                 {% else %}
                                    {{ splitReporterUuid|first == player.uuid ? player.batPlayer : '' }}
                                 {% endif %}
                              {% endfor%}
                           {% endfor %}
                        {% else %}
                           {% for player in players  %}
                              {{ replaceReporterUuid == player.uuid ? player.batPlayer : '' }}
                           {% endfor %}
                        {% endif %}
                     </p>
                     <p><b>Ip :</b> {{ report.reporterIp|replace({'/' : ''}) }}</p>
                     {% set splitReporterLocation = report.reporterLocation|split('/') %}
                     <p><b>Serveur:</b> {{ splitReporterLocation[0] }}</p>
                     <p>
                        <b>Coordonné :</b>
                        <b>X:</b> {{ splitReporterLocation[2] }}
                        <b>Y:</b> {{ splitReporterLocation[3] }}
                        <b>Z:</b> {{ splitReporterLocation[4] }}
                     </p>
                  </div>
                  <div class="col-lg-12 pt-3">
                     <p><b>Raison :</b> {{ report.reason }}</p>
                     {% set reporterMessages = report.reporterMessages|replace({'#next#': '<br>'}) %}
                     <b>Message : </b>
                     <p>{{ reporterMessages ? reporterMessages|raw : 'Pas de message' }}</p>
                  </div>
               </div>
            </div>
            <div class="col-lg-6 bd-show-report-right">
               <h4 class="text-center bd-show-report-title">Signalé</h4>
               <div class="row m-0 p-0">
                  <div class="col-lg-4 bd-show-report-separate">
                     <img class="d-inline-block" src="https://cravatar.eu/head/{{ report.reportedUuid }}/128" alt="">
                  </div>
                  <div class="col-lg-8 bd-show-report-separate">
                     <p>
                        <b>Signaleur :</b>
                        {% set replaceReportedUuid = report.reportedUuid|replace({'-': ''}) %}
                        {% for player in players %}
                           {{ replaceReportedUuid == player.uuid ? player.batPlayer : '' }}
                        {% endfor %}
                     </p>
                     <p><b>Ip :</b> {{ report.reportedIp|replace({'/' : ''}) }}</p>
                     {% set splitReportedLocation = report.reportedLocation|split('/') %}
                     <p><b>Serveur:</b> {{ splitReportedLocation[0] }}</p>
                     <p>
                        <b>Coordonné :</b>
                        <b>X:</b> {{ splitReportedLocation[2] }}
                        <b>Y:</b> {{ splitReportedLocation[3] }}
                        <b>Z:</b> {{ splitReportedLocation[4] }}
                     </p>
                  </div>
                  <div class="col-lg-12 pt-3">
                     <table class="table table-responsive-lg">
                        <thead class="table-dark">
                        <tr class="text-center">
                           <th>Gamemode</th>
                           <th>Au sol</th>
                           <th>Sneak</th>
                           <th>Sprint</th>
                           <th>Health</th>
                           <th>Food</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr class="bg-light text-center align-middle">
                           <td>{{ report.reportedGamemode }}</td>
                           <td>{{ report.reportedOnGround ? 'Oui' : 'Non' }}</td>
                           <td>{{ report.reportedSneak ? 'Oui' : 'Non' }}</td>
                           <td>{{ report.reportedSprint ? 'Oui' : 'Non' }}</td>
                           <td>{{ report.reportedHealth }}</td>
                           <td>{{ report.reportedFood }}</td>
                        </tr>
                        </tbody>
                     </table>
                     {% set reportedMessages = report.reportedMessages|replace({'#next#': '<br>'}) %}
                     <b>Message : </b>
                     <p>{{ reportedMessages ? reportedMessages|raw : 'Pas de message' }}</p>
                     {% set reportedEffects = report.reportedEffects|replace({':': ': Niveau : ', '/': ' / Temps : ' , ',': 's<br>'}) %}
                     <b>Effet de potion :</b>
                     <p>{{ reportedEffects|raw }}{{ reportedEffects ? 's' : 'Aucun effet' }}</p>
                  </div>
               </div>
            </div>
         </div>
      </div>
   </div>
{% endblock %}